# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2fb3c6b3f5c9b45cb70ee0f0777162188fdd16f0057d46bce9c8e1479912f48e18365dc39989dbc17aefb4199e98ffb592ee540112dd4a499fe2ccba9d3eb66

test:
  secret_key_base: 5fc6fca603cf23c097069e124235963495d2daaa26eaeb69b98b3d9918f53adbcd5c08f5e658a4ce8565956ffc6f29e2561e8da263632135d334b35f87e04e64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
